/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package grupos;

import java.awt.Color;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Luis
 */
public class panelClase extends javax.swing.JPanel {

    /**
     * Creates new form panelClase
     */
    public panelClase(String idioma,String maestro ) {
        initComponents();
        labelIdioma.setText(idioma);
        labelMaestro.setText(maestro);
        if (!idioma.equals("Sin Asignar")) {
            setBackground(new java.awt.Color(176, 209, 78));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMaestro = new javax.swing.JLabel();
        labelIdioma = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 251, 208));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelMaestro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaestro.setText("vacio");

        labelIdioma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdioma.setText("vacio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelMaestro)
                .addGap(18, 18, 18)
                .addComponent(labelIdioma)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIdioma;
    private javax.swing.JLabel labelMaestro;
    // End of variables declaration//GEN-END:variables
}
