/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package grupos;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import sql.ConexionSQLServer;
import utilerias.mensajesEnPantalla;
import ventanas.ventanaPrincipal;

/**
 *
 * @author Luis
 */
public class ventanaCrearGrupo extends javax.swing.JFrame {
     TreeMap<String, Integer> idsalones,idmaestro,ididioma,idTipoCurso;
     ListaDeGrupos p;
    /**
     * Creates new form ventanaCrearGrupo
     */
    public ventanaCrearGrupo(ListaDeGrupos aThis) {
        initComponents();
        p = aThis;
 
       llenarCombos();  this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
this.setVisible(true);
    }

    /**
     * This method sdsdis called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboSalon = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        comboIdioma = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        spinnerHoraInicio = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spinnerMinutosInicio = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinnerHoraTerminacion = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spinnerMinutosTerminacion = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboMaestro = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        comboNivel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Salon");

        jLabel2.setText("Tipo de Curso");

        jLabel3.setText("Idioma");

        comboIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdiomaActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora de Inicio");

        spinnerHoraInicio.setModel(new javax.swing.SpinnerNumberModel(12, 7, 20, 1));

        jLabel6.setText("Hora");

        spinnerMinutosInicio.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "30"}));

        jLabel4.setText("Minutos");

        jLabel7.setText("Minutos");

        jLabel8.setText("Hora de Terminacion");

        spinnerHoraTerminacion.setModel(new javax.swing.SpinnerNumberModel(12, 7, 20, 1));

        jLabel9.setText("Hora");

        spinnerMinutosTerminacion.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "30"}));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Maestro");

        comboMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMaestroActionPerformed(evt);
            }
        });

        jLabel11.setText("Nivel");

        comboNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        comboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(spinnerMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerHoraTerminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(11, 11, 11)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(spinnerMinutosTerminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboCurso, javax.swing.GroupLayout.Alignment.TRAILING, 0, 182, Short.MAX_VALUE)
                                    .addComponent(comboSalon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboIdioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMaestro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerMinutosInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerHoraTerminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerMinutosTerminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdiomaActionPerformed

    private void comboMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMaestroActionPerformed

    private void comboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNivelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TreeMap<String,Object> parametros = new TreeMap<>();
        String salon = comboSalon.getSelectedItem().toString().trim();
        int idsalon = idsalones.get(salon);
        String tipocurso = comboCurso.getSelectedItem().toString().trim();
        int idtipocurso = idTipoCurso.get(tipocurso);
        String maestro = comboMaestro.getSelectedItem().toString().trim();
        int idmaestr = idmaestro.get(maestro);
        String idioma = comboIdioma.getSelectedItem().toString().trim();
        int ididiom = ididioma.get(idioma);
        int nivel = Integer.parseInt( comboNivel.getSelectedItem().toString());
        

        String idCicloEscolar = ventanaPrincipal.idCicloEscolar;
        
        String hrInicio = spinnerHoraInicio.getModel().getValue().toString();
        String mnInicio = spinnerMinutosInicio.getModel().getValue().toString();
        String horaInicio = hrInicio + ":" + mnInicio + ":" + "00";
        Time timeInicio = Time.valueOf(horaInicio);
        
        String hrFinal =  spinnerHoraTerminacion.getModel().getValue().toString();
        String mnFinal = spinnerMinutosTerminacion.getModel().getValue().toString();
        String horaFinal = hrFinal + ":" + mnFinal + ":" + "00";
        Time timeFinal = Time.valueOf(horaFinal);
        
        if (hrInicio.length() == 1) {
            hrInicio = 0 + hrInicio;
        }
        if (hrFinal.length() == 1) {
            hrFinal = 0+ hrFinal;
        }
        String idGrupo = salon + idioma.substring(0, 3) + tipocurso.substring(0,3) +  nivel + idCicloEscolar  + hrInicio + mnInicio.charAt(0) + hrFinal + mnFinal.charAt(0);
        System.out.println(idGrupo);
        System.out.println(idGrupo.length());
        String claveGrupo = salon + hrInicio + mnInicio.charAt(0) + idCicloEscolar+tipocurso.substring(0, 1);
        
        parametros.put("1", idGrupo);
        parametros.put("2", idtipocurso);
        parametros.put("3", ididiom);
        parametros.put("4", idCicloEscolar);
        parametros.put("5", timeInicio);
        parametros.put("6", timeFinal);
        parametros.put("7", claveGrupo);
        parametros.put("8", idmaestr);
        parametros.put("9", nivel);
        parametros.put("10", idsalon);
        
      
        
        if ( ConexionSQLServer.insertarGrupo(parametros)) {
            dispose();
            mensajesEnPantalla.mensajeExitoso("Grupo registrado correctamente", "Registro");
            p.llenarTabla();
            p.setVisible(true);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCurso;
    private javax.swing.JComboBox comboIdioma;
    private javax.swing.JComboBox comboMaestro;
    private javax.swing.JComboBox comboNivel;
    private javax.swing.JComboBox comboSalon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spinnerHoraInicio;
    private javax.swing.JSpinner spinnerHoraTerminacion;
    private javax.swing.JSpinner spinnerMinutosInicio;
    private javax.swing.JSpinner spinnerMinutosTerminacion;
    // End of variables declaration//GEN-END:variables

    private void llenarCombos() {
         
        ididioma = new TreeMap<>();
        idmaestro = new TreeMap<>();
        idsalones = new TreeMap<>();
        idTipoCurso = new TreeMap<>();
        ResultSet rs = ConexionSQLServer.vistaIdiomas();
       String desc;
       int id;
        
        try {
             while (rs.next()) {
                desc = rs.getString(2).trim();
                id = rs.getInt(1);
                ididioma.put(desc, id);
                comboIdioma.addItem(desc);
             }} catch (SQLException ex) {
             Logger.getLogger(ventanaCrearGrupo.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
        
        rs = ConexionSQLServer.vistaIdSalon();
         try {
             while (rs.next()) {
                 desc = rs.getString(1).trim();
                 id = rs.getInt(2);
                 idsalones.put(desc, id);
                 comboSalon.addItem(desc);
             }} catch (SQLException ex) {
             Logger.getLogger(ventanaCrearGrupo.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         
         rs = ConexionSQLServer.vistaNombreMaIdioma();
         try {
             while (rs.next()) {
                 desc = rs.getString(2).trim();
                 id = rs.getInt(1);
                 idmaestro.put(desc, id);
                 comboMaestro.addItem(desc);
             }} catch (SQLException ex) {
             Logger.getLogger(ventanaCrearGrupo.class.getName()).log(Level.SEVERE, null, ex);
         }
        
         
         rs = ConexionSQLServer.vistaTipoCurso();
         try {
             while (rs.next()) {
                 desc = rs.getString(2).trim();
                 id = rs.getInt(1);
                 idTipoCurso.put(desc, id);
                 comboCurso.addItem(desc);
                         
             }} catch (SQLException ex) {
             Logger.getLogger(ventanaCrearGrupo.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    
    }
}
