/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ciclosEscolares;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import sql.ConexionSQLServer;
import utilerias.mensajesEnPantalla;
import ventanas.Login;
import ventanas.ventanaPrincipal;

/**
 *
 * @author Luis
 */
public class cambiarCicloEscolar extends javax.swing.JFrame {
    private TreeMap<Object, Object> idCiclos;
    ventanaPrincipal vp ;
    
    
    
    /**
     * Creates new form cambiarCicloEscolar
     */
    public cambiarCicloEscolar(ventanaPrincipal vp) {
        initComponents();
        this.vp = vp;
        llenarCombo();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
          this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboCiclos = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ciclo:");

        ComboCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCiclosActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ComboCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCiclosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCiclosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ventanaPrincipal.cicloEscolar = ComboCiclos.getSelectedItem().toString().trim();
        ventanaPrincipal.idCicloEscolar = (String) idCiclos.get(ComboCiclos.getSelectedItem().toString().trim());
        this.dispose();
             mensajesEnPantalla.mensajeExitoso("ciclo Escolar Cambiado",":3");        
        mensajesEnPantalla.mensajeExitoso(ventanaPrincipal.cicloEscolar,ventanaPrincipal.idCicloEscolar);
        System.out.println("sixe xdd" + ventanaPrincipal.getFrames().length);
    vp.setTitle(  "Ciclo escolar: "+ventanaPrincipal.cicloEscolar);
        vp.setVisible(true);
      
 
      new ventanaPrincipal("Deadmau5", ventanaPrincipal.cicloEscolar, ventanaPrincipal.idCicloEscolar);
 vp.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboCiclos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void llenarCombo() {
       try {
             idCiclos = new TreeMap<>();
             ResultSet rs  = ConexionSQLServer.vistaCicloEscolar();
    
             while (rs.next()) {
                String id = rs.getString(1).trim();
                String ciclo = rs.getString(2).trim();
                ComboCiclos.addItem(ciclo);
                idCiclos.put(ciclo, id);
                
             }
         
               
         
         
         } catch (SQLException ex) {
             Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
}
