/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examen;

import sql.ConexionSQLServer;
import utilerias.mensajesEnPantalla;

/**
 *
 * @author Luis
 */
public class panelInfoNivelAsignado extends javax.swing.JPanel {
  public int idalumno;
  String nombreAlumno;
  String nivelAlumno;
  String numeroDeControl;
  int idExamen;
    /**
     * Creates new form panelInfoNivelAsignado
     * @param idAlumno
     */
    public panelInfoNivelAsignado(int idAlumno,String nombreAlumno,String nivelAlumno,String numeroDeControl,int idExamen) {
        this.idalumno = idAlumno;
        this.nombreAlumno = nombreAlumno;
        this.nivelAlumno = nivelAlumno;
        this.numeroDeControl = numeroDeControl;
        this.idExamen = idExamen;
        initComponents();
        llenarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboNivel = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        labelNControl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNombre.setText("jLabel2");

        jLabel1.setText("Nivel");

        comboNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "Sin Asignar" }));

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelNControl.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(labelNControl, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(jLabel1)
                    .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(labelNControl))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (ConexionSQLServer.asignarNivelExamencolocacion(idalumno,comboNivel.getSelectedItem().toString(),idExamen)) {
          mensajesEnPantalla.mensajeExitoso("Niveles asignados correctamente", "Registro");   
        }
        
         
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboNivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNControl;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables

    private void llenarInfo() {
        this.labelNControl.setText(numeroDeControl);
        this.labelNombre.setText(nombreAlumno);
        this.comboNivel.setSelectedItem(nivelAlumno.trim());
    }
    
    
    public void asignar(){
    
      ConexionSQLServer.asignarNivelExamencolocacion(idalumno,comboNivel.getSelectedItem().toString(),idExamen);
    }
}
