/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import sql.ConexionSQLServer;
import utilerias.mensajesEnPantalla;

/**
 *
 * @author Luis
 */
public class VentanaAsignarNivelExamenColocacion extends javax.swing.JFrame {

    TreeMap<String, Integer> idAlumnosAsignados, idAlumnosNoAsigandos;
    ArrayList<panelInfoNivelAsignado> paneles;
    int idExamen;
    String nombre, fecha, hora, salon;

    /**
     * Creates new form VentanaAdmnExamenColocacion
     */
    public VentanaAsignarNivelExamenColocacion(int id, String nombre, String fecha, String hora, String salon) {
        initComponents();
        this.idExamen = id;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        informacionAdmExamenColocacion.setText("Examen asignado por el maestro" + " " + nombre + " " + "el dia" + fecha + " " + "a las" + " " + hora + " " + "en el salon" + " " + salon);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        llenarScrollPanelNiveles();
        setResizable(false);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informacionAdmExamenColocacion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelNiveles = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        informacionAdmExamenColocacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informacionAdmExamenColocacion.setAlignmentX(4.0F);

        panelNiveles.setLayout(new java.awt.GridLayout(1000, 1));
        jScrollPane3.setViewportView(panelNiveles);

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(informacionAdmExamenColocacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(informacionAdmExamenColocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < paneles.size(); i++) {

            System.out.println("nivelito !!!!!!!" + paneles.get(i).nivelAlumno);
            paneles.get(i).asignar();
        }
          mensajesEnPantalla.mensajeExitoso("Niveles asignados correctamente", "Registro");
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel informacionAdmExamenColocacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelNiveles;
    // End of variables declaration//GEN-END:variables

    private void llenarScrollPanelNiveles() {
        try {
            ResultSet rs = ConexionSQLServer.vistaInfoAlumnoExamenColocacion(idExamen);
            paneles = new ArrayList<>();
            System.out.println("broken");
            while (rs.next()) {
                System.out.println("tostring rs + " + rs.toString());

                String ncontrol = rs.getString(1);
                String nombre = rs.getString(2);
                int idAlumno = rs.getInt(3);
                String nivel = rs.getString(4);
                panelInfoNivelAsignado pt = new panelInfoNivelAsignado(idAlumno, nombre, nivel, ncontrol, idExamen);
                panelNiveles.add(pt);
                paneles.add(pt);

            }

            panelNiveles.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaAsignarNivelExamenColocacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
