/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import sql.ConexionSQLServer;
import utilerias.WindowHandler;
import utilerias.mensajesEnPantalla;

/**
 *
 * @author Luis
 */
public class VentanaAgregarFechaExam extends javax.swing.JFrame {


    int idExamen, idFecha;
    String entrada, fecha; 
    
    /**
     * Creates new form VentanaAgregarFechaExamLib
     */
    public VentanaAgregarFechaExam() {
        setLocation(200, 200);
        initComponents();
        entrada = "Agregar";
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        setVisible(true);
    
    }

    public VentanaAgregarFechaExam(int idFecha, String fecha) {
        setLocation(200, 200);
        initComponents();
        entrada = "Editar";
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        this.setTitle("Editando : " +fecha);
        this.idFecha = idFecha;
        setVisible(true);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionadorDeFecha = new com.toedter.calendar.JDateChooser();
        BotonAgregarfecha = new javax.swing.JButton();
        BotonCancelarFecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonAgregarfecha.setText("Agregar");
        BotonAgregarfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarfechaActionPerformed(evt);
            }
        });

        BotonCancelarFecha.setText("Cancelar");
        BotonCancelarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarFechaActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonAgregarfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonCancelarFecha)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seleccionadorDeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccionadorDeFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregarfecha)
                    .addComponent(BotonCancelarFecha))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarfechaActionPerformed
        // TODO add your handling code here:
        System.out.println("entrada :"+entrada);
        if (seleccionadorDeFecha.getDate()==null) {
            mensajesEnPantalla.mensajeError("No ha agregado una fecha", "Advertencia");
        } else {

            Date fecha = seleccionadorDeFecha.getDate();
            if (entrada.equals("Agregar")) {
                ConexionSQLServer.insertarFechaExamen(fecha);
                mensajesEnPantalla.mensajeExitoso("La fecha se ha agregado correctamente", "Agregar Fecha");
      
            } else {
                ConexionSQLServer.editarFechaExamen(idFecha, fecha);
                mensajesEnPantalla.mensajeExitoso("La fecha se ha modificado correctamente", "Editar Fecha");
                dispose();
   
            }
        }
      
    }//GEN-LAST:event_BotonAgregarfechaActionPerformed

    private void BotonCancelarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarFechaActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_BotonCancelarFechaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarfecha;
    private javax.swing.JButton BotonCancelarFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelFecha;
    private com.toedter.calendar.JDateChooser seleccionadorDeFecha;
    // End of variables declaration//GEN-END:variables
}
