/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package profesores;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import sql.ConexionSQLServer;
import utilerias.JTextFieldFilter;
import utilerias.mensajesEnPantalla;

/**
 *
 * @author Luis
 */
public class ventanaEmergenteMaestroIdioma extends javax.swing.JFrame {
      public String entrada; 
      public TreeMap<String,Integer> idiomas;
      public TreeMap<Integer,String> samoidi;
      int idMaestroIdioma;
      ListaDeProfesoresIdioma padre;
    /**
     * Creates new form ventanaEmergenteMaestroIdioma
     * @param padre
     */
    public ventanaEmergenteMaestroIdioma(ListaDeProfesoresIdioma padre) {
        entrada ="Agregar";
        this.padre = padre;
        initComponents();
        formatFields();
        llenarComboIdiomas();
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
           Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setVisible(true);
    }
    
    public ventanaEmergenteMaestroIdioma(int idMaestroIdioma,ListaDeProfesoresIdioma padre){
         entrada = "Editar";
         this.padre = padre;
         initComponents();
         formatFields();
         llenarComboIdiomas();
         this.idMaestroIdioma =  idMaestroIdioma;
         llenarCampos(idMaestroIdioma);
         
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setVisible(true);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//////////    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldNombreMaestroIdioma = new javax.swing.JTextField();
        fieldApellidoMaestroIdioma = new javax.swing.JTextField();
        fieldClaveMaestroIdioma = new javax.swing.JTextField();
        comboIdioma = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre(s)");

        jLabel2.setText("Apellidos");

        jLabel4.setText("Idioma");

        jLabel5.setText("Clave");

        fieldNombreMaestroIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreMaestroIdiomaActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldApellidoMaestroIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(80, 80, 80)
                            .addComponent(fieldNombreMaestroIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(102, 102, 102)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldClaveMaestroIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(comboIdioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNombreMaestroIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldApellidoMaestroIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldClaveMaestroIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nombre = fieldNombreMaestroIdioma.getText().toUpperCase();
        String apellido = fieldApellidoMaestroIdioma.getText().toUpperCase(Locale.FRENCH);
        String clave = fieldClaveMaestroIdioma.getText().toUpperCase();
        String idioma = comboIdioma.getSelectedItem().toString();
        int ididioma = idiomas.get(idioma);
        switch (entrada) {
            case "Agregar":
                
                if ( ConexionSQLServer.agregarMaestroIdioma(ididioma, nombre, apellido, clave)) {
                    System.out.println("------------------aceptar");
                padre.llenartreemapidmaestrosidiomas();
                padre.llenarTabla();
                padre.setVisible(true);
               
                dispose();
                  mensajesEnPantalla.mensajeExitoso("Maestro registrado correctamente", "Registro");
               
                }
               
             
                break;
            case "Editar":
                
                if (ConexionSQLServer.editarMaestroIdioma(ididioma, nombre, apellido, idMaestroIdioma, clave)) {
                   padre.llenartreemapidmaestrosidiomas();
                padre.llenarTabla();
                padre.setVisible(true);
                dispose();  
                 mensajesEnPantalla.mensajeExitoso("Maestro editado corretamente", "Registro");
               
                }
               
                break;

            default:
                System.out.println("");
        }


       
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldNombreMaestroIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreMaestroIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreMaestroIdiomaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboIdioma;
    private javax.swing.JTextField fieldApellidoMaestroIdioma;
    private javax.swing.JTextField fieldClaveMaestroIdioma;
    private javax.swing.JTextField fieldNombreMaestroIdioma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private void llenarCampos(int idMaestro) {
          try {
              
              ResultSet rs = ConexionSQLServer.vistaMaestroIdiomaEspecifico(idMaestro);
              rs.next();
              String nombre = rs.getString(2).trim();
              String apellido = rs.getString(3).trim();
              int idioma = rs.getInt(4);
              String clave = rs.getString(5).trim();
              
              comboIdioma.setSelectedItem(samoidi.get(idioma));
              fieldNombreMaestroIdioma.setText(nombre);
              fieldApellidoMaestroIdioma.setText(apellido);
              fieldClaveMaestroIdioma.setText(clave);
          } catch (SQLException ex) {
              Logger.getLogger(ventanaEmergenteMaestroIdioma.class.getName()).log(Level.SEVERE, null, ex);
          }
 
    
    
    }

    private void llenarComboIdiomas() {
          try {
              idiomas = new TreeMap<>();
              samoidi = new TreeMap<>();
       
              ResultSet rs = ConexionSQLServer.vistaIdiomas();
              
              while (rs.next()) {
               String idioma = rs.getString(2).trim();
              int idIdioma = rs.getInt(1);
              idiomas.put(idioma, idIdioma);
              samoidi.put(idIdioma, idioma);
              comboIdioma.addItem(idioma);
              } 
              
          
          
          
          } catch (SQLException ex) {
              Logger.getLogger(ventanaEmergenteMaestroIdioma.class.getName()).log(Level.SEVERE, null, ex);
          }
    
    
    }

    private void formatFields() {
     JTextFieldFilter tf = new JTextFieldFilter(JTextFieldFilter.ALPHA_NUMERICNS, 6);
     this.fieldClaveMaestroIdioma.setDocument(tf);
    }

 
}
